postgres:
  host: postgres
  port: 5432

server:
  port: :8080

quotations:
  - EUR
  - USD
  - MXN

quoteApi:
  url: "https://api.frankfurter.app/latest?from=%s&to=%s"

cron:
  location: Europe/Moscow
  period: "*/2 * * * *"

responseDelay: 5m